call pathogen#infect('~/.vim/bundle')
"call pathogen#runtime_append_all_bundles()
"call pathogen#helptags()

nmap :tb :TagbarToggle<CR>
nmap :nt :NERDTreeToggle<CR>
nmap :res :bo cw<CR>
map <F9> :bo cw<CR>:read !svn diff<CR>:set syntax=diff buftype=nofile<CR>gg

let g:NERDTreeDirArrows=0

colorscheme koehler
"set guifont=Monaco:h13

"syntax enable
"set t_Co=256
"let g:solarized_termcolors=16
"set background=dark
"colorscheme solarized

syntax on
filetype plugin indent on
set ofu=syntaxcomplete#Complete

"set t_Co=256

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set number
set ignorecase
set smartcase
set incsearch

