call pathogen#infect('~/.vim/bundle')
"call pathogen#runtime_append_all_bundles()
"call pathogen#helptags()

nmap :tag :TagbarToggle<CR>
nmap :nt :NERDTree<CR>

colorscheme koehler
set guifont=Monaco:h13

"syntax enable
"set t_Co=256
"let g:solarized_termcolors=16
"set background=dark
"colorscheme solarized

syntax on
filetype plugin indent on
set ofu=syntaxcomplete#Complete

"set t_Co=256

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent

set number
